### ISSUE TITLE
Doesn't pass admin validations?

### ISSUE THREAD

**Issue by waynelin** [skoczen/django-longer-username#3]
Hi there, 

Great app you have written here! However, I can't seem to get it to override the server side validations when in the django admin panel? 

Essentially, user creation with long usernames work on the client side of my site, but does not work when I want to create or change users on the admin panel. Am I missing something or is this not included yet? 

Wayne

**Comment by skoczen** [comment]
Nope, you're not missing anything - it's because of this bug: https://github.com/GoodCloud/django-longer-username/issues/1, 
which comes down to a regression in django that will be reverted in the next release. I've been looking for a way around it, but haven't come across anything yet.
