### ISSUE TITLE
Modifying the form widget attribute as well. 

### ISSUE THREAD

**Issue by waynelin** [skoczen/django-longer-username#4]
Hi there, 

Sorry for posting another issue, but I came across this and thought it may be useful to others. For the forms.py I also modified the `field.widget.attrs['maxlength']` rather than just `field.max_length`. Before doing this, my generated user creation form for the admin panel still wouldn't let me put in more than 30 characters since the html input element still had `max-length=30`. See final code below: 

``` python

def update_username_field(field):
    field.widget.attrs['maxlength'] = MAX_USERNAME_LENGTH()
    field.max_length = MAX_USERNAME_LENGTH()
    field.help_text = _("Required, %s characters or fewer. Only letters, numbers, and characters such as @.+_- are allowed." % MAX_USERNAME_LENGTH())

```

Cheers, 

Wayne

**Comment by skoczen** [comment]
This is great, if you want, go ahead an fork and toss a pull request my way with this improvement.
